stylesheet = ws ( charset ( Comment | Space | Cdo  | Cdc )* )* ( imports ( Comment | Space | Cdo | Cdc )* )* ( namespace ( Comment | Space | Cdo | Cdc )* )* ( nestedStatement ( Comment | Space | Cdo | Cdc )* )* ;
charset = Charset ws String ws ";" ws | Charset ws String ws ;
imports = Import ws ( String | Uri ) ws mediaQueryList ";" ws | Import ws ( String | Uri ) ws ";" ws | Import ws ( String | Uri ) ws mediaQueryList | Import ws ( String | Uri ) ws ;
namespace = Namespace ws (namespacePrefix ws)? ( String | Uri ) ws ";" ws | Namespace ws (namespacePrefix ws)? ( String | Uri ) ws ;
namespacePrefix = ident ;
media = Media ws mediaQueryList groupRuleBody ws ;
mediaQueryList = ( mediaQuery ( Comma ws mediaQuery )* )? ws ;
mediaQuery = ( MediaOnly |  Not )? ws mediaType ws ( And ws mediaExpression )* | mediaExpression ( And ws mediaExpression )* ;
mediaType = ident ;
mediaExpression = "(" ws mediaFeature ( ":" ws expr )? ")" ws ;
mediaFeature = ident ws ;
page = Page ws pseudoPage? "{" ws declaration? ( ";" ws declaration? )* "}" ws ;
pseudoPage = ":" ident ws ;
selectorGroup = selector ( Comma ws selector )* ;
selector = simpleSelectorSequence ws ( combinator simpleSelectorSequence ws )* ;
combinator =  Plus ws | Greater ws | Tilde ws | Space ws ;
simpleSelectorSequence = ( typeSelector | universal ) ( Hash | className | attrib | pseudo | negation )* | ( Hash | className | attrib | pseudo | negation )+ ;
typeSelector = typeNamespacePrefix? elementName ;
typeNamespacePrefix = ( ident | "*" )? "|" ;
elementName = ident ;
universal = typeNamespacePrefix? "*" ;
className = "." ident ;
attrib = "[" ws typeNamespacePrefix? ident ws ( ( PrefixMatch | SuffixMatch | SubstringMatch | "=" | Includes | DashMatch ) ws ( ident | String ) ws )? "]" ;
pseudo =  ":" ":"? ( ident | functionalPseudo ) ;
functionalPseudo = Function ws expression ")" ;
expression = ( ( Plus | Minus | Dimension | UnknownDimension | Number | String | ident ) ws )+ ;
negation = PseudoNot ws negationArg ws ")" ;
negationArg = typeSelector | universal | Hash | className | attrib | pseudo ;
operator =  "/" ws | Comma ws | Space ws | "=" ws ;
property = ident ws | Variable ws | "*" ident | "_" ident ;
ruleset = selectorGroup "{" ws declarationList? "}" ws | any* "{" ws declarationList? "}" ws ;
declarationList = ( ";" ws )* declaration ws ( ";" ws declaration? )* ;
declaration = property ":" ws expr prio? | property ":" ws value ;
prio = Important ws ;
value = ( any | block | atKeyword ws )+ ;
expr = term ( operator? term )* ;
term = number ws | percentage ws | dimension ws | String ws | UnicodeRange ws | ident ws | var | Uri ws | hexcolor | calc | function | unknownDimension ws | dxImageTransform ;
function = Function ws expr ")" ws ;
dxImageTransform = DxImageTransform ws expr ")" ws  ;
hexcolor = Hash ws ;
number = ( Plus | Minus )? Number ;
percentage = ( Plus | Minus )? Percentage ;
dimension =( Plus | Minus )? Dimension ;
unknownDimension = ( Plus | Minus )? UnknownDimension ;
any = ident ws | number ws | percentage ws | dimension ws | unknownDimension ws | String ws | Uri ws | Hash ws | UnicodeRange ws | Includes ws | DashMatch ws | ":" ws | Function ws ( any | unused )* ")" ws | "(" ws ( any | unused )* ")" ws | "[" ws ( any | unused )* "]" ws ;
atRule = atKeyword ws any* ( block  | ";" ws ) ;
atKeyword = "@" ident  ;
unused = block | atKeyword ws | ";" ws | Cdo ws | Cdc ws ;
block = "{" ws (  declarationList | nestedStatement | any | block | atKeyword ws | ";" ws )* "}" ws ;
nestedStatement = ruleset | media | page | fontFaceRule | keyframesRule | supportsRule | viewport | counterStyle | fontFeatureValuesRule | atRule ;
groupRuleBody = "{" ws nestedStatement* "}" ws ;
supportsRule = Supports ws supportsCondition ws groupRuleBody  ;
supportsCondition = supportsNegation | supportsConjunction | supportsDisjunction | supportsConditionInParens ;
supportsConditionInParens = "(" ws supportsCondition ws ")" | supportsDeclarationCondition | generalEnclosed ;
supportsNegation = Not ws Space ws supportsConditionInParens  ;
supportsConjunction = supportsConditionInParens ( ws Space ws And ws Space ws supportsConditionInParens ) ;
supportsDisjunction = supportsConditionInParens ( ws Space ws Or ws Space ws supportsConditionInParens ) ;
supportsDeclarationCondition = "(" ws declaration ")" ;
generalEnclosed = ( Function | "(" ) ( any | unused )* ")" ;
var = Var ws Variable ws ")" ws ;
calc = Calc ws calcSum ")" ws ;
calcSum = calcProduct ( Space ws ( Plus | Minus ) ws Space ws calcProduct )* ;
calcProduct = calcValue ( "*" ws calcValue | "/" ws number ws )* ;
calcValue = number ws | dimension ws | unknownDimension ws | percentage ws | "(" ws calcSum ")" ws ;
fontFaceRule = FontFace ws "{" ws fontFaceDeclaration? ( ";" ws fontFaceDeclaration? )* "}" ws ;
fontFaceDeclaration = property ":" ws expr | property ":" ws value;
keyframesRule = Keyframes ws Space ws ident ws "{" ws keyframesBlocks "}" ws ;
keyframesBlocks = ( keyframeSelector "{" ws declarationList? "}" ws )*  ;
keyframeSelector = ( From | To | Percentage ) ws ( Comma ws ( From | To | Percentage ) ws )* ;
viewport =  Viewport ws "{" ws declarationList? "}" ws ;
counterStyle = CounterStyle ws ident ws "{" ws declarationList? "}" ws ;
fontFeatureValuesRule = FontFeatureValues ws fontFamilyNameList ws "{" ws featureValueBlock* "}" ws ;
fontFamilyNameList = fontFamilyName ( ws Comma ws fontFamilyName )* ;
fontFamilyName = String | ident ( ws ident )* ;
featureValueBlock = featureType ws "{" ws featureValueDefinition? ( ws ";" ws featureValueDefinition? )* "}" ws ;
featureType = atKeyword ;
featureValueDefinition = ident ws ":" ws number ( ws number )* ;
ident = Ident | MediaOnly | Not | And | Or | From | To ;
ws = ( Comment | Space )* ;
Hex = /[0-9a-fA-F]/ ;
NewlineOrSpace = "\\r\\n" | /[ \\t\\r\\n\\f ]?/;
Unicode = "\\\\" Hex Hex? Hex? Hex? Hex? Hex? NewlineOrSpace  ;
Escape = Unicode | "\\\\" /~[\\r\\n\\f0-9a-fA-F]/ ;
Nmstart = /[_a-zA-Z]/ | Nonascii | Escape  ;
Nmchar = /[_a-zA-Z0-9\\-]/ | Nonascii | Escape ;
Comment = "/*" /(~[*])*/ /[*]+/ ( /~[\/*]/ /(~[*])*/ /[*]+/ )* "/" ;
Name =  Nmchar+ ;
Url = ( /[!#$%&*-~]/ | Nonascii | Escape )*  ;
Space = /[\\t\\r\\n\\f ]+/  ;
Whitespace = Space? ;
Newline = "\\n" | "\\r\\n" | "\\r" | "\\f" ;
ZeroToFourZeros = "0"? "0"? "0"? "0"?  ;
A = "a" | "A" | "\\\\" ZeroToFourZeros ("41"|"61") NewlineOrSpace ;
B = "b" | "B" | "\\\\" ZeroToFourZeros ("42"|"62") NewlineOrSpace ;
C = "c" | "C" | "\\\\" ZeroToFourZeros ("43"|"63") NewlineOrSpace  ;
D = "d" | "D" | "\\\\" ZeroToFourZeros ("44"|"64") NewlineOrSpace  ;
E = "e" | "E" | "\\\\" ZeroToFourZeros ("45"|"65") NewlineOrSpace  ;
F = "f" | "F" | "\\\\" ZeroToFourZeros ("46"|"66") NewlineOrSpace  ;
G = "g" | "G" | "\\\\" ZeroToFourZeros ("47"|"67") NewlineOrSpace | "\\\\g" | "\\\\G" ;
H = "h" | "H" | "\\\\" ZeroToFourZeros ("48"|"68") NewlineOrSpace | "\\\\h" | "\\\\H" ;
I = "i" | "I" | "\\\\" ZeroToFourZeros ("49"|"69") NewlineOrSpace | "\\\\i" | "\\\\I" ;
K = "k" | "K" | "\\\\" ZeroToFourZeros ("4b"|"6b") NewlineOrSpace | "\\\\k" | "\\\\K" ;
L = "l" | "L" | "\\\\" ZeroToFourZeros ("4c"|"6c") NewlineOrSpace | "\\\\l" | "\\\\L" ;
M = "m" | "M" | "\\\\" ZeroToFourZeros ("4d"|"6d") NewlineOrSpace | "\\\\m" | "\\\\M" ;
N = "n" | "N" | "\\\\" ZeroToFourZeros ("4e"|"6e") NewlineOrSpace | "\\\\n" | "\\\\N" ;
O = "o" | "O" | "\\\\" ZeroToFourZeros ("4f"|"6f") NewlineOrSpace | "\\\\o" | "\\\\O" ;
P = "p" | "P" | "\\\\" ZeroToFourZeros ("50"|"70") NewlineOrSpace | "\\\\p" | "\\\\P" ;
Q = "q" | "Q" | "\\\\" ZeroToFourZeros ("51"|"71") NewlineOrSpace | "\\\\q" | "\\\\Q" ;
R = "r" | "R" | "\\\\" ZeroToFourZeros ("52"|"72") NewlineOrSpace | "\\\\r" | "\\\\R" ;
S = "s" | "S" | "\\\\" ZeroToFourZeros ("53"|"73") NewlineOrSpace | "\\\\s" | "\\\\S" ;
T = "t" | "T" | "\\\\" ZeroToFourZeros ("54"|"74") NewlineOrSpace | "\\\\t" | "\\\\T" ;
U = "u" | "U" | "\\\\" ZeroToFourZeros ("55"|"75") NewlineOrSpace | "\\\\u" | "\\\\U" ;
V = "v" | "V" | "\\\\" ZeroToFourZeros ("56"|"76") NewlineOrSpace | "\\\\v" | "\\\\V" ;
W = "w" | "W" | "\\\\" ZeroToFourZeros ("57"|"77") NewlineOrSpace | "\\\\w" | "\\\\W" ;
X = "x" | "X" | "\\\\" ZeroToFourZeros ("58"|"78") NewlineOrSpace | "\\\\x" | "\\\\X" ;
Y = "y" | "Y" | "\\\\" ZeroToFourZeros ("59"|"79") NewlineOrSpace | "\\\\y" | "\\\\Y" ;
Z = "z" | "Z" | "\\\\" ZeroToFourZeros ("5a"|"7a") NewlineOrSpace | "\\\\z" | "\\\\Z" ;
DashChar = "-" | "\\\\" ZeroToFourZeros "2d" NewlineOrSpace ;
Cdo = "<!--" ;
Cdc = "-->" ;
Includes = "~=" ;
DashMatch = "|=" ;
Hash = "#" Name ;
Import = "@" I M P O R T ;
Page = "@" P A G E ;
Media = "@" M E D I A ;
Namespace = "@" N A M E S P A C E ;
Charset = "@charset " ;
Important = "!" ( Space | Comment )* I M P O R T A N T ;
FontRelative  = Number E M | Number E X | Number C H | Number R E M ;
ViewportRelative = Number V W | Number V H | Number V M I N | Number V M A X ;
AbsLength = Number P X | Number C M | Number M M | Number I N | Number P T | Number P C | Number Q ;
Angle = Number D E G | Number R A D | Number G R A D | Number T U R N ;
Time = Number M S | Number S ;
Freq = Number H Z | Number K H Z ;
Percentage = Number "%" ;
Uri = U R L "(" Whitespace String Whitespace ")" | U R L "(" Whitespace Url Whitespace ")" ;
UnicodeRange = /[u|U]/ "+?" "?"? "?"? "?"? "?"? "?"? | /[u|U]/ "+" Hex "?"? "?"? "?"? "?"? "?"? | /[u|U]/ "+" Hex Hex "?"? "?"? "?"? "?"? | /[u|U]/ "+" Hex Hex Hex "?"? "?"? "?"? | /[u|U]/ "+" Hex Hex Hex Hex "?"? "?"? | /[u|U]/ "+" Hex Hex Hex Hex Hex "?"? ;
MediaOnly = O N L Y ;
Not = N O T ;
And = A N D ;
Resolution = Number D P I | Number D P C M | Number D P P X  ;
Length = AbsLength | FontRelative | ViewportRelative  ;
Dimension = Length | Time | Freq | Resolution | Angle ;
UnknownDimension = Number Ident ;
Nonascii = /~[\\u0000-\\u007f]/ ;
Plus = "+"  ;
Minus = "-" ;
Greater =  ">" ;
Comma = "," ;
Tilde = "~" ;
PseudoNot = ":" N O T "(" ;
Number = /[0-9]+/ | /[0-9]*/ "." /[0-9]+/ ;
String = "\"" ( /~[\\n\\r\\f\\\\\"]/ | "\\\\" Newline | Nonascii | Escape )* "\"" | "'" ( /~[\\n\\r\\f\\\\']/  | "\\\\" Newline | Nonascii | Escape )* "'" ;
PrefixMatch = "^=" ;
SuffixMatch = "$=" ;
SubstringMatch = "*=" ;
FontFace = "@" F O N T DashChar F A C E ;
Supports = "@" S U P P O R T S ;
Or = O R ;
VendorPrefix = "-" M O Z "-" | "-" W E B K I T "-" | "-" O "-"  ;
Keyframes = "@" VendorPrefix? K E Y F R A M E S ;
From = F R O M ;
To = T O ;
Calc = "calc(" ;
Viewport = "@" V I E W P O R T ;
CounterStyle =  "@" C O U N T E R DashChar S T Y L E  ;
FontFeatureValues = "@" F O N T DashChar F E A T U R E DashChar V A L U E S ;
DxImageTransform = "progid:DXImageTransform.Microsoft." Function ;
Variable = "--" Nmstart Nmchar* ;
Var = "var(" ;
Ident = "-"? Nmstart Nmchar* ;
Function = Ident "(" ;

